### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: jcifs/Credentials

### ISSUE THREAD

**Issue by vgardner** [LWB-IT/docker-manifoldcf#1]
When building this project I'm getting the following error in the logs. Have you encountered this before?

`'org.apache.manifoldcf.crawler.connectors.meridio.MeridioConnector'``
manifoldcf_1  | Successfully registered repository connector 'org.apache.manifoldcf.crawler.connectors.jira.JiraRepositoryConnector'
manifoldcf_1  | Successfully registered repository connector 'org.apache.manifoldcf.crawler.connectors.jdbc.JDBCConnector'
manifoldcf_1  | Exception in thread "main" java.lang.NoClassDefFoundError: jcifs/Credentials
manifoldcf_1  | 	at java.lang.Class.forName0(Native Method)
manifoldcf_1  | 	at java.lang.Class.forName(Class.java:348)
manifoldcf_1  | 	at org.apache.manifoldcf.core.system.ManifoldCFResourceLoader.findClass(ManifoldCFResourceLoader.java:149)
manifoldcf_1  | 	at org.apache.manifoldcf.core.system.ManifoldCF.findClass(ManifoldCF.java:1511)
manifoldcf_1  | 	at org.apache.manifoldcf.core.interfaces.ConnectorFactory.getThisConnectorRaw(ConnectorFactory.java:144)
manifoldcf_1  | 	at org.apache.manifoldcf.core.interfaces.ConnectorFactory.getThisConnectorNoCheck(ConnectorFactory.java:118)
manifoldcf_1  | 	at org.apache.manifoldcf.core.interfaces.ConnectorFactory.installThis(ConnectorFactory.java:48)
manifoldcf_1  | 	at org.apache.manifoldcf.crawler.interfaces.RepositoryConnectorFactory.install(RepositoryConnectorFactory.java:100)
manifoldcf_1  | 	at org.apache.manifoldcf.crawler.connmgr.ConnectorManager.registerConnector(ConnectorManager.java:180)
manifoldcf_1  | 	at org.apache.manifoldcf.crawler.system.ManifoldCF.registerConnectors(ManifoldCF.java:672)
manifoldcf_1  | 	at org.apache.manifoldcf.crawler.system.ManifoldCF.reregisterAllConnectors(ManifoldCF.java:160)
manifoldcf_1  | 	at org.apache.manifoldcf.jettyrunner.ManifoldCFJettyRunner.main(ManifoldCFJettyRunner.java:239)
manifoldcf_1  | Caused by: java.lang.ClassNotFoundException: jcifs.Credentials
manifoldcf_1  | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
manifoldcf_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
manifoldcf_1  | 	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
manifoldcf_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
manifoldcf_1  | 	... 12 more`

**Comment by thomasheyl** [comment]
I'm getting the same error. I use the manifold in version 2.x. 
At the moment, i dont know, where to search, cause the jcifs package ist stable over one and a half year.

**Comment by thomasheyl** [comment]
I found the problem, i will fix it in the next days.

**Comment by care4truth** [comment]
Hey!! Did you get a chance to fix this issue.

**Comment by thomasheyl** [comment]
Hello, the issue is fixed. You still got a problem?
